FROM openjdk:18.0.2-jdk

# Copy local code to the container image.
#WORKDIR /app



COPY  target/customermsrestdatajpa-*.jar /demo.jar



# Run the web service on container startup.
 CMD  java -jar /demo.jar

