FROM maven:3-openjdk-11 as mavenstage
# Copy local code to the container image.
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests=true

FROM tomcat:8.5.85-jre11
WORKDIR webapps
# Copy the jar to the production image from the builder stage.
COPY --from=mavenstage /app/target/demo-*.war ./demo.war
#expose port in container for traffic from outer world
EXPOSE 8080
RUN rm -rf ROOT && mv demo.war ROOT.war