FROM maven:3-openjdk-11 as mavenstage
# Copy local code to the container image.
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests=true


FROM adoptopenjdk/openjdk16:alpine-jre
# Copy the jar to the production image from the builder stage.
COPY --from=mavenstage /app/target/demo-*.war /demo.war

#expose port in container for traffic from outer world
EXPOSE 8585
CMD java -jar /demo.war
